// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HomepageNav: typeof import('./components/homepage-nav.vue')['default']
    MdiCartPlus: typeof import('~icons/mdi/cart-plus')['default']
    MdiChevronDownCircleOutline: typeof import('~icons/mdi/chevron-down-circle-outline')['default']
    MdiFilter: typeof import('~icons/mdi/filter')['default']
    MdiFilterOutline: typeof import('~icons/mdi/filter-outline')['default']
    MdiMinus: typeof import('~icons/mdi/minus')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiStar: typeof import('~icons/mdi/star')['default']
    MdiStarOutline: typeof import('~icons/mdi/star-outline')['default']
    Petra: typeof import('./components/petra.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
